name = "zeroagent-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_WC_PROJECT_ID = "a50f9d9b4b801a6ccc0c3ba7ce02e68f"
